### ISSUE TITLE
separate gazebo topic sender and airsim api interface with UDP communication

### ISSUE THREAD

**Issue by JasonBrauer** [JasonBrauer/airsim-integration#14]
- each will be run in a separate docker container with their respective dependencies

**Comment by murphym18** [comment]
I added a message counter to the `PoseMessage` struct. Since we're using UDP, we're supposed to handle packets that arrive out of order. If we don't, our simulation might jump forward and backwards in time (this problem is sometimes called _rubber banding_). But with a message counter we can reject any message that isn't the newest.

Here's some pseudo code that shows how our message receiver might work:

```python
msg_num = message.message_counter

if last_msg_num < msg_num:
    update_drone(msg)
    last_msg_num = msg_num
else: 
    log("rejecting the message")

```

**Comment by murphym18** [comment]
We need to update [`struct Pose`](https://github.com/JasonBrauer/airsim-integration/blob/ad4c56b3a27a98cfa63c2da67285fed5fd278416/gazebo/src/pose.hpp) (or our usage of it) so that our fields are converted to an interchangeable binary format. Right now all of the fields are of type `double`. Here are some ideas of how we might convert them:

1. we store each field as a fixed point 64 bit integer with _Network Byte-Ordering_. For example, each field could be converted from a double to a u64 with `x = (uint64_t) x * 1e5`
2. we find a way to convert it to an IEEE 754 double. This might be easy or it might be hard...
3. we change the field to a string with a fixed length (maybe a 16 character ASCII string?) then we use [`atof`](https://cplusplus.com/reference/cstdlib/atof/) and [`strtod`](https://cplusplus.com/reference/cstdlib/strtod/) to convert it.

I'm not sure there exists a host-to-net functions or macros (like `htonl`) for floating point values. Maybe there's a lib we can use. But it seems that platforms can store floats in their own binary format. 

I think the first option would be easiest. We can change the fields to type `uint64_t`. Then we can pick a scale. For example, if we multiply our x, y, and z by `1e5` then the drone is limited to a grid where each grid line is 10 microns apart... But that's probably fine (our sensors don't operate on that small a difference).

**Comment by JasonBrauer** [comment]
Thanks for bringing this up. I also like option number 1 you proposed. I am submitting a PR with an implementation. I kept the _double_ post struct and introduced a private uint64_t version within the sender class. I thought that might make the interface simpler. The conversions are done within the class before sending.

Let me know if you would prefer the public pose struct just be a uint64_t.

**Comment by JasonBrauer** [comment]
@murphym18 not ready to merge to main bc I still have a little cleanup to do, but udp streaming gazebo messages to airsim is working on the `dev-gz-sender` branch. 

`cmake` should work to build both the sender and receiver. 

for the receiver, have the required env variable AIRSIM_ROOT to point to the Airsim install directory

**Comment by murphym18** [comment]
@JasonBrauer I added a `htonll` and `ntohll` implementation. But I used a C++ 20 feature to do it. So I updated the `CMakeLists.txt` (it was using C++ 11). I hope that doesn't break anything for you.

As far as I can tell, the host-to-net functions work when the CPU is big endian or little endian (but if it's _mixed_ endian then it won't work...). To detect the endianess I used the enum `std::endian` which is part of the C++ 20 standard. 

I also merged dev-gz-sender.

**Comment by murphym18** [comment]
Oh yeah, here's how I tested the `htonll` function:

```cpp
#include <iostream>
#include <cstdint>
#include <arpa/inet.h>
#include <bit>

inline constexpr int64_t reverse_bytes(const int64_t value) {
    // if we have 0x 22222222 11111111
    auto hb = (int64_t) htonl(value) << 32; // 11111111 00000000
    auto lb = (int64_t) htonl(value >> 32); // 00000000 22222222
    return hb + lb; // 11111111 22222222
}

inline constexpr int64_t htonll(const int64_t value) {
    // This is a "constexpr if statement" If native == little, then the compiler
    // will discarded the false branch otherwise the true branch is discarded.
    if constexpr (std::endian::native == std::endian::little) {
        return reverse_bytes(value);
    }
    else {
        return value;
    }
}

inline constexpr int64_t ntohll(const int64_t value) {
    return htonll(value);
}


int main() {
    using std::cout;

    bool is_little_endian = (std::endian::native == std::endian::little);
    if (is_little_endian) {
        cout << "this machine is little endian" << std::endl;
    } else {
        cout << "this machine is big endian" << std::endl;
    }

    uint16_t x {0x1234};
    cout << "x = 0x" << std::hex << x << std::endl;

    x = htons(x);
    cout << "x = htons(x)" << std::endl;
    cout << "x = 0x" << std::hex << x << std::endl;
    
    x = ntohs(x);
    cout << "x = ntohs(x)" << std::endl;
    cout << "x = 0x" << std::hex << x << std::endl;

    cout<< "Now doing the same operation on int64_t" << std::endl;
    uint64_t forward {0xA1020304050607E8};
    cout << "forward = 0x" << std::hex << forward << std::endl;

    uint64_t backward = htonll(forward);
    cout << "backward = htonll(forward)" << std::endl;
    cout << "backward = 0x" << std::hex << backward << std::endl;

    uint64_t forward2 = ntohll(backward);
    cout << "forward2 = ntohll(backward)" << std::endl;
    cout << "forward2 = 0x" << std::hex << forward2 << std::endl;
    cout << "forward2 == forward ? " << std::boolalpha << (forward2 == forward) << std::endl;

    return 0;
}
```

**Comment by JasonBrauer** [comment]
Thanks for including your test. The implementation is really clear in reverse_bytes.

I am running into a compilation issue since `htonll` and `ntohll` exist in the C library on my machine. 

```
In file included from /Users/jasonbrauer/CodeRepo/airsim-integration/gazebo/src/udp_receiver.cpp:2:
/Users/jasonbrauer/CodeRepo/airsim-integration/gazebo/airsim/../src/net_endian.hpp:35:27: error: cannot redeclare builtin function '__builtin_constant_p'
inline constexpr uint64_t htonll(const uint64_t value) 
```

I'll have to look into how to allow the functions to be overridden. 

Oh, and no issues with jumping to the C++20 standard. I was using C++11 since that was in the original GazeboDrone program. Haven't had a need to change it until now.

**Comment by murphym18** [comment]
To fix the problem on macOS, maybe we should use a namespace?

I pushed a commit that moves the host-to-net functions to `namespace net_bits` and I updated the usage of `htonll` and `ntohll` to use the namespace.

Perhaps that's not the best solution though. We could have also selectively declared `htonll` too but I figured it would be easier if we don't have compiler directives like `#if`... Though I'm on the fence about that... 

On the one hand, we could create bugs that appear on one platform but not the other when we use the `#if` directive to selectively compile source for each platform.

But on the other hand, maybe the macOS htonll functions are better in some way? I'm not sure.

Hopefully my latest commit works.

**Comment by JasonBrauer** [comment]
I don't think the macos htonll functions are better enough to deal with
potential tricky bugs due to two different implementations. Also, the macos
htonll takes uint64 and returns uint64. So there is an extra conversion to
deal with / handle based on one or the other implementation.

I like the namespace solution. If htonll's are added or removed for
different OSs, we won't have to deal with that dependency.

**Comment by murphym18** [comment]
Thanks for sharing that. I didn't know the built-in one uses uint64 and only uint64. It's reassuring to know that my code is flawed just like Apple's.

Because one of the problems with my code is that the type is hard-coded. I ended up copy-pasting the code so that we could have an implementation for uint64 and int64. I'm pretty sure there's a better way using templates or something... 

In fact, I tried to use [byteswap](https://en.cppreference.com/w/cpp/numeric/byteswap) from C++23. `byteswap` reverses the bytes and it uses a template type so it works on any type of int. But it's not in my version of `libstdc++`.

So given all that, the code is probably good enough.

**Comment by JasonBrauer** [comment]
> So given all that, the code is probably good enough.

Totally agree. I tried to compile again after you added the net_bits namespace. Ran into the same issue with the compiler complaining about `htonll` and `ntohll` being redefined. I think the namespace had no effect because `htonll` and `ntohll` are C functions. 

So I tried redefining the two functions before the `arpa/inet.h` import then undefining them after the import. 
https://stackoverflow.com/questions/17614686/how-to-undef-a-library-function-to-use-our-version-of-same-function

This worked. However, the compiler threw warnings about it. At that point, I decided maybe we should just use different function names and avoid the problem altogether. So I chose `ntoh64` and `hton64` as the new names and pushed the changes. 

I am curious about the use of `constexpr.` It certainly doesn't hurt anything, but won't the functions you defined in net_endian.hpp have to evaluate at runtime and not compile time? They don't receive constant values at compile time. Instead they receive changing values at runtime. As a test I swapped `constexpr` for `hton64` to `consteval`. My understanding of `consteval` is that for functions it is the same as `constexpr`, but forces the compiler to evaluate at compile time. The compiler will fail if it cannot. In the case where I swapped to `consteval` the compiler did fail because the inputs were not const at compile time:

```
In file included from /Users/jasonbrauer/CodeRepo/airsim-integration/gazebo/src/udp_sender.cpp:2:
/Users/jasonbrauer/CodeRepo/airsim-integration/gazebo/gazebo/../src/net_endian.hpp:26:16: error: call to consteval function 'net_bits::hton64' is not a constant expression
        return hton64(value);
               ^
/Users/jasonbrauer/CodeRepo/airsim-integration/gazebo/gazebo/../src/net_endian.hpp:26:23: note: function parameter 'value' with unknown value cannot be used in a constant expression
        return hton64(value);
```

**Comment by murphym18** [comment]
>I am curious about the use of constexpr. It certainly doesn't hurt anything, but won't the functions you defined in net_endian.hpp have to evaluate at runtime and not compile time? 

Yes that is correct. And originally I wrote `constexpr` because I wanted a stronger kind of `inline`. But now I think `inline` + `constexpr` might be redundant. At the time I didn't know the following:

>A constexpr specifier used in a function or [static](https://en.cppreference.com/w/cpp/language/static) data member (since C++17) declaration implies inline.

I found this quote at [cppreference.com](https://en.cppreference.com/w/cpp/language/constexpr)

So it's my understanding that a `constexpr` function is:
- inlined when the definition is part of the translation unit
- linked and called like any other function when it's declared but the definition is not a part of the translation unit

I guess that means it's compiled like a regular function too? That way we can still link to it (theoretically).

But in our case, the definition is provided in the header file, so we don't need the linker and the compiler should have inlined it through-out the program. 


Also I didn't know about `consteval`. Thanks for sharing that. The way you used it was a cool trick. 

I was also wondering: does the function get _inlined_ if we call it from some other translation unit? Here's an example, suppose we compile this code:

```cpp
#include <cstdint>
#include <iostream>

inline constexpr int64_t net_endian::hton64(const int64_t value);

int main() {
    int64_t x = 1;
    std::cout << "Please enter an integer: ";
    std::cin >> x;
    x = net_endian::hton64(x);
    cout << "hton64(x) = 0x" << std::hex << x << std::endl;
}
```
In this case, we only _declared_ the `hton64` function so our translation unit doesn't have a definition. But it is defined in our other translation units.

I did some digging and I guess the compiler makes the `net_endian` functions available for external translation units too (like the example above). And in case we invoke `hton64`, the linker will do a plain-old function call... (At least, I think that's what happens but I didn't try it).

I found this somewhat surprising because we have at least two object files with a `hton64` definition. So what definition does the linker choose? I guess the C++ spec gets around this problem by requiring every definition to be the same. I thought that was pretty clever and clumsy at the same time 🤣.

Apparently, you can cause "undefined behavior" if you change the definition between Translation Units. For example, we could create a problem if we:
1. compiled an object file that uses the net_endian functions as they exist in `net_endian.hpp`
2. changed the definition of the net_endian functions and compiled a second object file.
3. compiled a third object file like the example above. (It declares a net_endian function and calls it, but doesn't define it)
4. _link_ them all together into a program.

My guess is the linker will error out (if we're lucky) or it will choose one of the definitions randomly. But I guess it depends on how the linker is implemented and other details. But this could be incredibly frustrating! Imagine fixing an inline function and having the bug re=appear sometimes but not other times! That could drive someone crazy 🤣. C/C++ is one heck of a language. I'm starting to understand why weird things can happen if I don't `make clean` before I `make`.

I didn't realize these feature interactions could cause these sorts of "anomalies." Next time, I'll think twice before I add a `constexpr` or `inline` specifier. I think as a rule of thumb I'll only `inline` or `constexpr` a function if it's static or if it's defined in a header file.

**Comment by JasonBrauer** [comment]
I think as a rule of thumb 

> I'll only inline or constexpr a function if it's static or if it's defined in a header file.

That seems like a good rule of thumb!

>  I guess the C++ spec gets around this problem by requiring every definition to be the same. I thought that was pretty clever and clumsy at the same time

That is really good to know. I like that we dove into how the `inline` and `constexpr` work. I have learned a lot!

After your post here, I continued looking into inline and constexpr and found a couple additional interesting things:
- `inline` is really just a suggestion to the compiler. The compiler may decide that the performance benefit of including the function inline isn't worth it and ignore the specifier. This is different than a preprocessor macro definition which will definitely get inserted during the preprocessor step. 
- Apparently `inline` is assumed if you [define a function in the header file](https://learn.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-170#example-1), so adding the `inline` specifier at all is redundant

On another (hopefully quicker topic) - have you used an c++ libraries for unit testing that you would suggest? In a quick search I found the the [boost unit test library](https://www.boost.org/doc/libs/1_46_0/libs/test/doc/html/utf.html) seems to be one of the most popular.
